@startuml
left to right direction

actor "Taller" as Taller


rectangle "Sistema" {
  usecase "Visualizar Listado de Usuarios" as UC4
  usecase "Registrar Usuario" as UC4_1
  UC4 ..> UC4_1 : <<include>>
}


Taller --> UC4



@enduml
