@startuml
left to right direction
actor "Cliente (Conductor)" as Cliente
actor "Taller" as Taller
actor "Técnico" as Tecnico

rectangle "Sistema" {
  usecase "Cerrar Sesión" as UC2
}

Cliente --> UC2
Taller --> UC2
Tecnico --> UC2
@enduml