@startuml
left to right direction
actor "Cliente" as C

rectangle "Sistema" {
  usecase "CU-10: Visualizar estado de la solicitud" as CU10
  usecase "CU-09: Reportar emergencia" as CU09
}


C --> CU10
CU10 ..> CU09 : <<include>>
@enduml