@startuml
left to right direction


actor "Cliente" as C
actor "Taller" as T
rectangle "Sistema" {
usecase "CU-14: Descargar reporte PDF" as CU14
usecase "CU-23: Visualizar Resumen Estructurado" as CU23
}
C --> CU14
T --> CU14
CU14 ..> CU23 : <<include>>
@enduml