@startuml
left to right direction


actor "Taller" as T
rectangle "Sistema" {
usecase "CU-18: Aceptar / Rechazar Solicitud" as CU18
usecase "CU-17: Ver Resumen IA (Pre-aceptación)" as CU17
}
T --> CU18
CU18 ..> CU17 : <<include>>
@enduml