@startuml
left to right direction
skinparam usecase {
  BackgroundColor LightCyan
  BorderColor DarkBlue
}

actor "Taller" as T
rectangle "Sistema" {
usecase "CU-19: Asignar Técnico a Incidente" as CU19
usecase "CU-18: Aceptar / Rechazar Solicitud" as CU18
}
T --> CU19
CU19 ..> CU18 : <<include>>
@enduml