@startuml
left to right direction


actor "Técnico" as Tech
rectangle "Sistema" {
usecase "CU-20: Actualizar Estado del Servicio" as CU20
usecase "CU-24: Recibir Notificaciones Push" as CU24
}

Tech --> CU20
CU20 ..> CU24 : <<include>>
@enduml