@startuml
left to right direction
actor "Técnico" as Tech
actor "Taller" as T
rectangle "Sistema" {

usecase "CU-21: Gestionar disponibilidad del técnico" as CU21
}    
Tech --> CU21
T --> CU21
@enduml