@startuml
left to right direction
actor "Cliente" as C
actor "Taller" as T
actor "Técnico" as Tech
rectangle "Sistema" {

usecase "CU-23: Visualizar resumen estructurado del incidente" as CU23
}
C --> CU23
T --> CU23
Tech --> CU23
@enduml
