@startuml
left to right direction
actor "Cliente" as C
actor "Taller" as T
actor "Técnico" as Tech

rectangle "Sistema" {

usecase "CU-24: Recibir notificaciones Push en tiempo real" as CU24
}
C --> CU24
T --> CU24
Tech --> CU24
@enduml