@startuml
left to right direction
actor "Cliente" as C
actor "Taller" as T

rectangle "Sistema" {
  usecase "CU-06: Recuperar contraseña" as CU06
  usecase  "CU-01: Iniciar sesión" as CU01
}

C --> CU06
T --> CU06

CU06 ..> CU01 : <<include>>
@enduml
