@startuml
left to right direction
actor "Cliente" as C
actor "Taller" as T
actor "Tecnico" as A

rectangle "Sistema" {
	usecase "CU-07: Gestionar perfil de usuario" as CU07
}

C --> CU07
T --> CU07
A --> CU07
@enduml