@startuml
left to right direction
skinparam actorStyle stickman
skinparam packageStyle rectangle
skinparam shadowing false

' --- ESTILOS ---
skinparam usecase {
  BackgroundColor LightCyan
  BorderColor DarkBlue
  FontSize 12
}

' --- ACTORES ---
actor "Cliente" as C
actor "Taller" as T
actor "Técnico" as Tech


    
  rectangle "Diagrama General de Casos de Uso" {
        usecase "CU-01: Iniciar sesión" as CU01
        usecase "CU-02: Cerrar sesión" as CU02
        usecase "CU-03: Registrar Usuario" as CU03
        usecase "CU-04: Visualizar Listado de Usuarios" as CU04
        usecase "CU-05: Visualizar Bitácora" as CU05
  


        usecase "CU-06: Recuperar contraseña" as CU06
        usecase "CU-07: Gestionar perfil" as CU07
        usecase "CU-08: Registrar vehículo" as CU08
        usecase "CU-09: Reportar emergencia" as CU09
        usecase "CU-10: Visualizar estado" as CU10
        usecase "CU-11: Ver ETA" as CU11
        usecase "CU-12: Redirección (WhatsApp/Tel)" as CU12
        usecase "CU-13: Realizar pago" as CU13
    

        usecase "CU-14: Descargar reporte PDF" as CU14
        usecase "CU-15: Registrar técnico" as CU15
        usecase "CU-16: Ver solicitudes disponibles" as CU16
        usecase "CU-17: Resumen estructurado (IA)" as CU17
        usecase "CU-18: Aceptar / Rechazar Solicitud" as CU18
        usecase "CU-19: Asignar técnico a incidente" as CU19
        usecase "CU-20: Actualizar Estado del Servicio" as CU20
        usecase "CU-21: Gestionar disponibilidad técnico" as CU21
        usecase "CU-22: Historial y Métricas" as CU22
    

  
        usecase "CU-23: Ficha técnica detallada" as CU23
        usecase "CU-24: Recibir notificaciones Push" as CU24
        usecase "CU-25: Gestionar cobro comisión (10%)" as CU25
    

    ' --- RELACIONES INCLUDES ---
    CU06 ..> CU01 : <<include>>
    CU10 ..> CU09 : <<include>>
    CU18 ..> CU17 : <<include>>
    CU20 ..> CU24 : <<include>>
    CU14 ..> CU23 : <<include>>
}

' --- VÍNCULOS CLIENTE ---
C -- CU01
C -- CU02
C -- CU03
C -- CU06
C -- CU07
C -- CU08
C -- CU09
C -- CU10
C -- CU11
C -- CU12
C -- CU13
C -- CU24

' --- VÍNCULOS TALLER ---
T -- CU01
T -- CU02
T -- CU04
T -- CU05
T -- CU07
T -- CU14
T -- CU15
T -- CU16
T -- CU17
T -- CU18
T -- CU19
T -- CU21
T -- CU22
T -- CU25

' --- VÍNCULOS TÉCNICO ---
Tech -- CU01
Tech -- CU02
Tech -- CU07
Tech -- CU20
Tech -- CU23
Tech -- CU24

@enduml