@startuml
top to bottom direction
skinparam shadowing false
skinparam componentStyle uml2
skinparam nodesep 40
skinparam ranksep 60

skinparam component {
    BackgroundColor #FADBD8
    BorderColor #922B21
    BorderThickness 1.2
}
skinparam interface {
    BackgroundColor #FADBD8
    BorderColor #922B21
}
skinparam arrow {
    Color #555555
    Thickness 1.2
}

frame "cmp 4. Reportes y Notificaciones" {
    package "Reportes y Notificaciones" {
        
        ' Capa de Vistas
        component "BitacoraView.tsx" as V1
        component "AIResumenView.tsx" as V2
        component "HistoryView.tsx" as V3

        ' Interfaces
        interface " " as I1
        interface " " as I2

        ' Capa de Controladores
        component "LogRouter.py" as C1
        component "ReporteRouter.py" as C2

        ' Capa de Modelos
        component "Bitácora" as M1
        component "ResumenIA" as M2

        ' Conexiones
        V1 --( I1
        I1 -- C1

        V2 --( I2
        V3 --( I2
        I2 -- C2

        C1 ..> M1
        C2 ..> M2
    }
}
@enduml