@startuml
top to bottom direction
skinparam shadowing false
skinparam componentStyle uml2
skinparam nodesep 40
skinparam ranksep 60

skinparam component {
    BackgroundColor #FADBD8
    BorderColor #922B21
    BorderThickness 1.2
}
skinparam interface {
    BackgroundColor #FADBD8
    BorderColor #922B21
}
skinparam arrow {
    Color #555555
    Thickness 1.2
}

frame "cmp 2. Gestión de Asistencia" {
    package "Gestión de Asistencia" {
        
        ' Capa de Vistas
        component "ReportEmergency.tsx" as V1
        component "TrackStatus.tsx" as V2
        component "PaymentView.tsx" as V3
        component "RequestsList.tsx" as V4

        ' Interfaces
        interface " " as I1
        interface " " as I2
        interface " " as I3

        ' Capa de Controladores
        component "IncidenteRouter.py" as C1
        component "PagoRouter.py" as C2

        ' Capa de Modelos
        component "Incidente" as M1
        component "Multimedia" as M2
        component "Pago" as M3

        ' Conexiones
        V1 --( I1
        V2 --( I1
        V4 --( I1
        I1 -- C1

        V3 --( I2
        I2 -- C2

        C1 ..> M1
        C1 ..> M2
        C2 ..> M3
        C2 ..> M1
    }
}
@enduml