@startuml
top to bottom direction
skinparam shadowing false
skinparam componentStyle uml2
skinparam nodesep 40
skinparam ranksep 60

skinparam component {
    BackgroundColor #FADBD8
    BorderColor #922B21
    BorderThickness 1.2
}
skinparam interface {
    BackgroundColor #FADBD8
    BorderColor #922B21
}
skinparam arrow {
    Color #555555
    Thickness 1.2
}

frame "cmp 1. Gestión de Usuarios" {
    package "Gestión de Usuarios" {
        
        ' Capa de Vistas (React)
        component "LoginView.tsx" as V1
        component "RegisterView.tsx" as V2
        component "ProfileView.tsx" as V3
        component "UserListView.tsx" as V4

        ' Interfaces de conexión
        interface " " as I1
        interface " " as I2
        interface " " as I3

        ' Capa de Controladores (FastAPI)
        component "AuthRouter.py" as C1
        component "UserRouter.py" as C2

        ' Capa de Modelos (Base de Datos)
        component "Usuario" as M1
        component "Vehículo" as M2

        ' Conexiones Vista -> Controlador
        V1 --( I1
        V2 --( I1
        I1 -- C1

        V3 --( I2
        V4 --( I3
        I2 -- C2
        I3 -- C2

        ' Conexiones Controlador -> Modelo
        C1 ..> M1
        C2 ..> M1
        C2 ..> M2
    }
}
@enduml