"""'Initial_Reset'

Revision ID: 63e1dd55dd7b
Revises: 
Create Date: 2026-04-18 22:46:11.512530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e1dd55dd7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidad_id'), 'especialidad', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('comision_porcentaje', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taller_id'), 'taller', ['id'], unique=False)
    op.create_table('horario_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=15), nullable=True),
    sa.Column('hora_apertura', sa.Time(), nullable=True),
    sa.Column('hora_cierre', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horario_taller_id'), 'horario_taller', ['id'], unique=False)
    op.create_table('taller_especialidad',
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.Column('nivel_experiencia', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('taller_id', 'especialidad_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('clave_hash', sa.String(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('tabla_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=True),
    sa.Column('valor_anterior', sa.JSON(), nullable=True),
    sa.Column('valor_nuevo', sa.JSON(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_id'), 'bitacora', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiracion', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('token_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_fcm', sa.Text(), nullable=False),
    sa.Column('plataforma', sa.String(length=20), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_dispositivo_id'), 'token_dispositivo', ['id'], unique=False)
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('tipo_combustible', sa.String(length=30), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculo_id'), 'vehiculo', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculo_placa'), 'vehiculo', ['placa'], unique=True)
    op.create_table('incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('transcripcion_audio', sa.Text(), nullable=True),
    sa.Column('clasificacion_ia', sa.String(length=100), nullable=True),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidente_id'), 'incidente', ['id'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=20), nullable=True),
    sa.Column('url_archivo', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencia_id'), 'evidencia', ['id'], unique=False)
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacion_id'), 'notificacion', ['id'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comision_plataforma', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_id'), 'pago', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_notificacion_id'), table_name='notificacion')
    op.drop_table('notificacion')
    op.drop_index(op.f('ix_evidencia_id'), table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index(op.f('ix_incidente_id'), table_name='incidente')
    op.drop_table('incidente')
    op.drop_index(op.f('ix_vehiculo_placa'), table_name='vehiculo')
    op.drop_index(op.f('ix_vehiculo_id'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_index(op.f('ix_token_dispositivo_id'), table_name='token_dispositivo')
    op.drop_table('token_dispositivo')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_bitacora_id'), table_name='bitacora')
    op.drop_table('bitacora')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('taller_especialidad')
    op.drop_index(op.f('ix_horario_taller_id'), table_name='horario_taller')
    op.drop_table('horario_taller')
    op.drop_index(op.f('ix_taller_id'), table_name='taller')
    op.drop_table('taller')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_especialidad_id'), table_name='especialidad')
    op.drop_table('especialidad')
    # ### end Alembic commands ###
