@startuml
left to right direction

skinparam nodesep 40
skinparam ranksep 70
skinparam packageStyle folder
skinparam arrow {
  Color #2c3e50
  Thickness 1.5
}

package "Capa de Presentación (Frontend)" {
    [Aplicación Web\n(Talleres)] as Web #LightCyan
    [Aplicación Móvil\n(Clientes y Técnicos)] as Movil #LightGreen
}

package "Capa de Lógica de Negocio (Backend FastAPI)" {
    package "1. Gestión de Usuarios" as P1 #White
    package "2. Gestión de Asistencia" as P2 #White
    package "3. Gestión Técnico" as P3 #White
    package "4. Reportes y Notificaciones" as P4 #White
}

' Relaciones de comunicación
Web ..> P1
Web ..> P2
Web ..> P3
Web ..> P4

Movil ..> P1
Movil ..> P2
Movil ..> P3
Movil ..> P4

@enduml