@startuml
left to right direction

skinparam shadowing false
skinparam packageStyle strictuml
skinparam nodesep 30
skinparam ranksep 80

skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BackgroundColor White
  BorderColor Black
}
skinparam arrow {
  Color #2c3e50
  Thickness 1.2
}

actor "Taller\n(Web)" as Taller
actor "Técnico\n(Móvil)" as Tecnico

package "3. Gestión Técnico" #LightBlue {
    usecase "CU-15: Registrar técnico" as CU15
    usecase "CU-19: Asignar técnico a incidente" as CU19
    usecase "CU-20: Actualizar estado del servicio" as CU20
    usecase "CU-21: Gestionar disponibilidad del técnico" as CU21
    usecase "CU-25: Gestionar cobro de comisión" as CU25

    ' Relaciones de dependencia UML 2.5
    CU19 ..> CU21 : <<include>>
    CU19 <.. CU20 : <<extend>>
}

' Relaciones del Taller
Taller -- CU15
Taller -- CU19
Taller -- CU21
Taller -- CU25

' Relaciones del Técnico
CU20 -- Tecnico

@enduml