@startuml
left to right direction

skinparam shadowing false
skinparam packageStyle strictuml
skinparam nodesep 30
skinparam ranksep 80

skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BackgroundColor White
  BorderColor Black
}
skinparam arrow {
  Color #2c3e50
  Thickness 1.2
}

actor "Taller\n(Web)" as Taller
actor "Cliente\n(Móvil)" as Cliente

package "2. Gestión de Asistencia" #LightBlue {
    usecase "CU-09: Reportar emergencia" as CU9
    usecase "CU-10: Visualizar estado de la solicitud" as CU10
    usecase "CU-11: Visualizar tiempo estimado de llegada" as CU11
    usecase "CU-13: Realizar pago del servicio" as CU13
    usecase "CU-16: Visualizar solicitudes de auxilio disponibles" as CU16
    usecase "CU-18: Aceptar / Rechazar solicitud" as CU18

    ' Relaciones de dependencia UML 2.5
    CU18 ..> CU16 : <<include>>
    CU10 <.. CU11 : <<extend>>
}

' Relaciones del Taller
Taller -- CU16
Taller -- CU18

' Relaciones del Cliente
CU9 -- Cliente
CU10 -- Cliente
CU11 -- Cliente
CU13 -- Cliente

@enduml