@startuml
left to right direction

skinparam shadowing false
skinparam packageStyle strictuml
skinparam nodesep 20
skinparam ranksep 80

skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BackgroundColor White
  BorderColor Black
}
skinparam arrow {
  Color #2c3e50
  Thickness 1.2
}

actor "Taller\n(Web)" as Taller
actor "Cliente\n(Móvil)" as Cliente

package "4. Reportes y Notificaciones" #LightBlue {
    usecase "CU-05: Visualizar bitácora" as CU5
    usecase "CU-12: Redirección de comunicación (Teléfono, Chat)" as CU12
    usecase "CU-14: Descargar reporte técnico (PDF)" as CU14
    usecase "CU-17: Ver información estructurada del incidente (Resumen IA)" as CU17
    usecase "CU-22: Visualizar historial de atenciones y métricas" as CU22
    usecase "CU-23: Visualizar resumen estructurado del incidente" as CU23
    usecase "CU-24: Recibir notificaciones Push en tiempo real" as CU24

    ' Relaciones de dependencia UML 2.5
    CU23 <.. CU14 : <<extend>>
    CU23 <.. CU17 : <<extend>>
}

' Relaciones del Taller
Taller -- CU5
Taller -- CU12
Taller -- CU14
Taller -- CU17
Taller -- CU22
Taller -- CU23
Taller -- CU24

' Relaciones del Cliente
CU12 -- Cliente
CU14 -- Cliente
CU22 -- Cliente
CU23 -- Cliente
CU24 -- Cliente

@enduml