@startuml
left to right direction

' Configuración estricta UML 2.5 sin actores
skinparam packageStyle strictuml
skinparam nodesep 20
skinparam ranksep 80
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}

package "2. Gestión de Asistencia" #LightBlue {
    usecase "CU-09: Reportar emergencia" as CU9
    usecase "CU-10: Visualizar estado de la solicitud" as CU10
    usecase "CU-11: Visualizar tiempo estimado de llegada" as CU11
    usecase "CU-13: Realizar pago del servicio" as CU13
    usecase "CU-16: Visualizar solicitudes de auxilio disponibles" as CU16
    usecase "CU-18: Aceptar / Rechazar solicitud" as CU18


    ' En Gestión de Asistencia


CU11 ..> CU10 : <<extend>> 
' (Ver el tiempo estimado es opcional al visualizar el estado de la solicitud)

' Relaciones entre Paquetes (Inter-módulos)


}
