@startuml
left to right direction

' Configuración estricta UML 2.5 sin actores
skinparam packageStyle strictuml
skinparam nodesep 20
skinparam ranksep 80
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}

package "3. Gestión Técnico" #LightBlue {
 usecase "CU-15: Registrar técnico" as CU15
    usecase "CU-19: Asignar técnico a incidente" as CU19
    usecase "CU-20: Actualizar estado del servicio" as CU20
    usecase "CU-21: Gestionar disponibilidad del técnico" as CU21
    usecase "CU-25: Gestionar cobro de comisión" as CU25


    CU19 ..> CU20 : <<extend>>



}
